#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.2.8f1_ff5b465c8d13"
#define UNITY_VERSION_FULL_NICE "2019.2.8f1 (ff5b465c8d13)"
#define UNITY_VERSION_BLD 16735046
#define UNITY_VERSION_DATE 1569459281
#define UNITY_VERSION_WIN "2019.2.8.16735046"
#define UNITY_VERSION_BRANCH "2019.2/staging"
